CREATE VIEW [dbo].[vw_Product_1]
	AS 
	SELECT [TenantId]
      ,[Id]
      ,[Name]
      ,[ProductNumber]
      ,[Description]
      ,[CategoryId]
      ,[MakeFlag]
      ,[FinishedGoodsFlag]
      ,[Color]
      ,[SafetyStockLevel]
      ,[ReorderPoint]
      ,[StandardCost]
      ,[ListPrice]
      ,[Size]
      ,[SizeUnitMeasureCode]
      ,[WeightUnitMeasureCode]
      ,[Weight]
      ,[DaysToManufacture]
      ,[ProductLine]
      ,[Class]
      ,[Style]
      ,[ProductSubCategoryId]
      ,[ProductModelId]
      ,[SellStartDate]
      ,[SellEndDate]
      ,[DiscontinuedDate]
      ,[rowguid]
      ,[ModifiedDate]
  FROM [dbo].[Product]

